services:
  rescan:
    restart: unless-stopped 
    container_name: rescan 
    build: .
    hostname: rescan 
    networks: 
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true 
    volumes: 
      - /opt/rescan:/app/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt

networks: 
  saltbox:
    external: true 